const alumniData = [
  // REGISTERED ALUMNI (26)
  {
    first_name: "Georgios",
    last_name: "Papadopoulos",
    gender: "male",
    graduation_year: 2020,
    course: "BSc (Hons) Computer Science",
    school: "School of Computing",
    bio: "Passionate about web development and AI. Currently working on several open source projects.",
    current_position: "Software Developer",
    company: "Intrasoft International",
    contact_email: "georgios.p@example.com",
    phone: "+30 694 555 1001",
    linkedin: "https://linkedin.com/in/georgiospap",
    role: "registered_alumni"
  },
  {
    first_name: "Eleni",
    last_name: "Alexiou",
    gender: "female",
    graduation_year: 2021,
    course: "BA (Hons) Business Management",
    school: "Business School",
    bio: "Marketing specialist with a passion for digital strategies. Interested in brand development and consumer behavior.",
    current_position: "Marketing Coordinator",
    company: "Antenna Group",
    contact_email: "eleni.a@example.com",
    phone: "+30 695 555 1002",
    linkedin: "https://linkedin.com/in/elenialexiou",
    role: "registered_alumni"
  },
  {
    first_name: "Dimitris",
    last_name: "Vasiliadis",
    gender: "male",
    graduation_year: 2019,
    course: "BSc (Hons) Physiotherapy",
    school: "School of Health & Sport Sciences",
    bio: "Sports enthusiast and certified physiotherapist. Specializing in athletic injuries and rehabilitation.",
    current_position: "Physiotherapist",
    company: "Athens Medical Group",
    contact_email: "dimitris.v@example.com",
    phone: "+30 697 555 1003",
    linkedin: "https://linkedin.com/in/dimitrisv",
    role: "registered_alumni"
  },
  {
    first_name: "Maria",
    last_name: "Kyriakidou",
    gender: "female",
    graduation_year: 2022,
    course: "MSc Psychology of Addictions and Behavioural Change",
    school: "School of Psychology",
    bio: "Dedicated to helping people overcome addictive behaviors. Research interest in cognitive behavioral therapy.",
    current_position: "Psychologist",
    company: "Hygeia Hospital",
    contact_email: "maria.k@example.com",
    phone: "+30 698 555 1004",
    linkedin: "https://linkedin.com/in/mariakyriakidou",
    role: "registered_alumni"
  },
  {
    first_name: "Nikos",
    last_name: "Andreou",
    gender: "male",
    graduation_year: 2018,
    course: "MBA Global",
    school: "Business School",
    bio: "Business consultant with expertise in international markets. Passionate about startups and innovation.",
    current_position: "Business Development Manager",
    company: "Alpha Bank",
    contact_email: "nikos.a@example.com",
    phone: "+30 699 555 1005",
    linkedin: "https://linkedin.com/in/nikosandreou",
    role: "registered_alumni"
  },
  {
    first_name: "Sofia",
    last_name: "Papanikolaou",
    gender: "female",
    graduation_year: 2023,
    course: "BA (Hons) Early Childhood Studies",
    school: "School of Education",
    bio: "Passionate about early childhood development and creative learning methods. Advocate for inclusive education.",
    current_position: "Early Years Educator",
    company: "Campion School Athens",
    contact_email: "sofia.p@example.com",
    phone: "+30 694 555 1006",
    linkedin: "https://linkedin.com/in/sofiapapanikolaou",
    role: "registered_alumni"
  },
  {
    first_name: "Andreas",
    last_name: "Nikolaou",
    gender: "male",
    graduation_year: 2020,
    course: "MSc Civil Engineering and Construction",
    school: "School of Engineering",
    bio: "Civil engineer with focus on sustainable construction methods. Interested in smart city development.",
    current_position: "Project Engineer",
    company: "AKTOR S.A.",
    contact_email: "andreas.n@example.com",
    phone: "+30 695 555 1007",
    linkedin: "https://linkedin.com/in/andreasnikolaou",
    role: "registered_alumni"
  },
  {
    first_name: "Christina",
    last_name: "Georgiou",
    gender: "female",
    graduation_year: 2019,
    course: "MA Leading Tourism & Hospitality",
    school: "School of Tourism & Hospitality",
    bio: "Hospitality professional with experience in luxury hotels. Passionate about exceptional customer experiences.",
    current_position: "Hotel Manager",
    company: "Costa Navarino Resort",
    contact_email: "christina.g@example.com",
    phone: "+30 697 555 1008",
    linkedin: "https://linkedin.com/in/christinageorgiou",
    role: "registered_alumni"
  },
  {
    first_name: "Panagiotis",
    last_name: "Antoniou",
    gender: "male",
    graduation_year: 2021,
    course: "BSc (Hons) Cyber Security",
    school: "School of Computing",
    bio: "Cybersecurity specialist with a focus on network security and ethical hacking. CISSP certified.",
    current_position: "Security Analyst",
    company: "COSMOTE",
    contact_email: "panagiotis.a@example.com",
    phone: "+30 698 555 1009",
    linkedin: "https://linkedin.com/in/panagiotisamtoniou",
    role: "registered_alumni"
  },
  {
    first_name: "Katerina",
    last_name: "Dimitriou",
    gender: "female",
    graduation_year: 2022,
    course: "BA (Hons) Fashion Design & Marketing",
    school: "School of Arts & Design",
    bio: "Fashion designer with a passion for sustainable fashion. Interested in integrating technology in textile design.",
    current_position: "Fashion Designer",
    company: "Zeus+Dione",
    contact_email: "katerina.d@example.com",
    phone: "+30 699 555 1010",
    linkedin: "https://linkedin.com/in/katerinadimitriou",
    role: "registered_alumni"
  },
  {
    first_name: "Vasilis",
    last_name: "Konstantinou",
    gender: "male",
    graduation_year: 2018,
    course: "ΜΒΑ Global Shipping",
    school: "School of Shipping",
    bio: "Maritime professional with experience in international shipping operations. Interested in sustainable shipping practices.",
    current_position: "Shipping Operations Manager",
    company: "Diana Shipping Inc.",
    contact_email: "vasilis.k@example.com",
    phone: "+30 694 555 1011",
    linkedin: "https://linkedin.com/in/vasiliskonstantinou",
    role: "registered_alumni"
  },
  {
    first_name: "Ioanna",
    last_name: "Papadaki",
    gender: "female",
    graduation_year: 2020,
    course: "BSc (Hons) Applied Psychology",
    school: "School of Psychology",
    bio: "Clinical psychologist specializing in adolescent mental health. Advocate for mental health awareness.",
    current_position: "Clinical Psychologist",
    company: "Metropolitan Hospital",
    contact_email: "ioanna.p@example.com",
    phone: "+30 695 555 1012",
    linkedin: "https://linkedin.com/in/ioannapapadaki",
    role: "registered_alumni"
  },
  {
    first_name: "Kostas",
    last_name: "Theodorou",
    gender: "male",
    graduation_year: 2023,
    course: "MSc Digital Marketing",
    school: "Business School",
    bio: "Digital marketing expert with focus on SEO and content marketing strategies. Google Analytics certified.",
    current_position: "Digital Marketing Specialist",
    company: "Ogilvy Greece",
    contact_email: "kostas.t@example.com",
    phone: "+30 697 555 1013",
    linkedin: "https://linkedin.com/in/kostastheodorou",
    role: "registered_alumni"
  },
  {
    first_name: "Alexandra",
    last_name: "Markopoulou",
    gender: "female",
    graduation_year: 2019,
    course: "BA (Hons) English Language and TESOL",
    school: "School of Education",
    bio: "TEFL educator with experience teaching English in diverse environments. Passionate about language acquisition methodologies.",
    current_position: "English Language Teacher",
    company: "British Council Athens",
    contact_email: "alexandra.m@example.com",
    phone: "+30 698 555 1014",
    linkedin: "https://linkedin.com/in/alexandramarkopoulou",
    role: "registered_alumni"
  },
  {
    first_name: "Thanos",
    last_name: "Antonopoulos",
    gender: "male",
    graduation_year: 2020,
    course: "BEng (Hons) Mechanical Engineering & Design",
    school: "School of Engineering",
    bio: "Mechanical engineer specializing in renewable energy systems. Passionate about sustainable technology solutions.",
    current_position: "Mechanical Engineer",
    company: "Terna Energy",
    contact_email: "thanos.a@example.com",
    phone: "+30 699 555 1015",
    linkedin: "https://linkedin.com/in/thanosantonopoulos",
    role: "registered_alumni"
  },
  {
    first_name: "Evgenia",
    last_name: "Koutsoukou",
    gender: "female",
    graduation_year: 2022,
    course: "MSc Counselling and Psychology in Educational Settings",
    school: "School of Psychology",
    bio: "School psychologist focused on creating supportive educational environments. Interested in child development psychology.",
    current_position: "School Counselor",
    company: "ACS Athens International School",
    contact_email: "evgenia.k@example.com",
    phone: "+30 694 555 1016",
    linkedin: "https://linkedin.com/in/evgeniakoutsoukou",
    role: "registered_alumni"
  },
  {
    first_name: "Stefanos",
    last_name: "Panagiotou",
    gender: "male",
    graduation_year: 2021,
    course: "BSc (Hons) Computer Games Programming",
    school: "School of Computing",
    bio: "Game developer with experience in Unity and Unreal Engine. Passionate about creating immersive gaming experiences.",
    current_position: "Game Developer",
    company: "Pollfish",
    contact_email: "stefanos.p@example.com",
    phone: "+30 695 555 1017",
    linkedin: "https://linkedin.com/in/stefanospanagiotou",
    role: "registered_alumni"
  },
  {
    first_name: "Danai",
    last_name: "Lambrou",
    gender: "female",
    graduation_year: 2020,
    course: "MSc Human Resource Management",
    school: "Business School",
    bio: "HR professional specializing in talent acquisition and employee development. Certified in HR management.",
    current_position: "HR Specialist",
    company: "Coca-Cola Hellas",
    contact_email: "danai.l@example.com",
    phone: "+30 697 555 1018",
    linkedin: "https://linkedin.com/in/danailambrou",
    role: "registered_alumni"
  },
  {
    first_name: "Alexis",
    last_name: "Georgiades",
    gender: "male",
    graduation_year: 2019,
    course: "BA (Hons) Professional Culinary Arts",
    school: "School of Tourism & Hospitality",
    bio: "Chef specializing in Mediterranean cuisine with a focus on modern techniques. Passionate about local ingredients.",
    current_position: "Head Chef",
    company: "Funky Gourmet",
    contact_email: "alexis.g@example.com",
    phone: "+30 698 555 1019",
    linkedin: "https://linkedin.com/in/alexisgeorgiades",
    role: "registered_alumni"
  },
  {
    first_name: "Athina",
    last_name: "Christodoulou",
    gender: "female",
    graduation_year: 2021,
    course: "MA Education (TESOL): Teaching English to Speakers of Other Languages",
    school: "School of Education",
    bio: "TESOL educator with experience in curriculum development. Passionate about innovative language teaching methodologies.",
    current_position: "Academic Coordinator",
    company: "Doukas School",
    contact_email: "athina.c@example.com",
    phone: "+30 699 555 1020",
    linkedin: "https://linkedin.com/in/athinachristodoulou",
    role: "registered_alumni"
  },
  {
    first_name: "Ioannis",
    last_name: "Makris",
    gender: "male",
    graduation_year: 2022,
    course: "MSc Sustainable Architecture & Healthy Buildings",
    school: "School of Engineering",
    bio: "Architect specializing in sustainable design. Passionate about creating environmentally responsible buildings.",
    current_position: "Sustainable Design Architect",
    company: "Tsolakis Architects",
    contact_email: "ioannis.m@example.com",
    phone: "+30 694 555 1021",
    linkedin: "https://linkedin.com/in/ioannismakris",
    role: "registered_alumni"
  },
  {
    first_name: "Despina",
    last_name: "Katsarou",
    gender: "female",
    graduation_year: 2020,
    course: "MSc Forensic Psychology (with Psychotherapy)",
    school: "School of Psychology",
    bio: "Forensic psychologist with experience in criminal profiling. Research interests include criminal behavior analysis.",
    current_position: "Forensic Psychologist",
    company: "Hellenic Police",
    contact_email: "despina.k@example.com",
    phone: "+30 695 555 1022",
    linkedin: "https://linkedin.com/in/despinakatsarou",
    role: "registered_alumni"
  },
  {
    first_name: "Ahmed",
    last_name: "El-Masri",
    gender: "male",
    graduation_year: 2021,
    course: "MSc Big Data Analytics",
    school: "School of Computing",
    bio: "Data scientist with expertise in machine learning and predictive analytics. Passionate about solving complex problems with data.",
    current_position: "Data Scientist",
    company: "OTE Group",
    contact_email: "ahmed.m@example.com",
    phone: "+30 695 555 1128",
    linkedin: "https://linkedin.com/in/ahmedelmasri",
    role: "registered_alumni"
  },
  {
    first_name: "Giorgi",
    last_name: "Maisuradze",
    gender: "male",
    graduation_year: 2019,
    course: "MSc Cyber Security",
    school: "School of Computing",
    bio: "Cybersecurity expert specializing in threat intelligence and security architecture. CISSP and CEH certified.",
    current_position: "Information Security Analyst",
    company: "Piraeus Bank",
    contact_email: "giorgi.m@example.com",
    phone: "+30 698 555 1125",
    linkedin: "https://linkedin.com/in/giorgimaisuradze",
    role: "registered_alumni"
  },
  {
    first_name: "Arben",
    last_name: "Hoxha",
    gender: "male",
    graduation_year: 2021,
    course: "BSc (Hons) Computer Science",
    school: "School of Computing",
    bio: "Software developer with expertise in mobile applications. Open source contributor and tech community organizer.",
    current_position: "Mobile Developer",
    company: "Beat",
    contact_email: "arben.h@example.com",
    phone: "+30 695 555 1120",
    linkedin: "https://linkedin.com/in/arbenhoxha",
    role: "registered_alumni"
  },
  // APPLIED ALUMNI (4)
  {
    first_name: "Christos",
    last_name: "Mavrakis",
    gender: "male",
    graduation_year: 2023,
    course: "BSc (Hons) Computer Science",
    school: "School of Computing",
    bio: "Recent graduate interested in AI and machine learning. Looking for opportunities in the tech industry.",
    current_position: "Graduate",
    company: "",
    contact_email: "christos.m@example.com",
    phone: "+30 694 555 2001",
    linkedin: "https://linkedin.com/in/christosmavrakis",
    role: "applied_alumni"
  },
  {
    first_name: "Anastasia",
    last_name: "Nikolaidou",
    gender: "female",
    graduation_year: 2023,
    course: "BA (Hons) Business Management",
    school: "Business School",
    bio: "Business administration graduate with interest in project management. Certified in PRINCE2 methodology.",
    current_position: "Junior Project Manager",
    company: "Forthnet",
    contact_email: "anastasia.n@example.com",
    phone: "+30 695 555 2002",
    linkedin: "https://linkedin.com/in/anastasianikolaidou",
    role: "applied_alumni"
  },
  {
    first_name: "Stavros",
    last_name: "Michalopoulos",
    gender: "male",
    graduation_year: 2022,
    course: "MSc Mechanical Engineering and Design",
    school: "School of Engineering",
    bio: "Mechanical engineer with focus on automotive design. Experience in CAD/CAM technologies and 3D printing.",
    current_position: "Design Engineer",
    company: "Aegean Airlines",
    contact_email: "stavros.m@example.com",
    phone: "+30 697 555 2003",
    linkedin: "https://linkedin.com/in/stavrosmichalopoulos",
    role: "applied_alumni"
  },
  {
    first_name: "Efthymia",
    last_name: "Papadopoulou",
    gender: "female",
    graduation_year: 2023,
    course: "MSc Psychology of Addictions and Behavioural Change",
    school: "School of Psychology",
    bio: "Psychology graduate specializing in addiction therapy. Interested in research on cognitive behavioral therapies.",
    current_position: "Intern Psychologist",
    company: "Dromokaiteio Psychiatric Hospital",
    contact_email: "efthymia.p@example.com",
    phone: "+30 698 555 2004",
    linkedin: "https://linkedin.com/in/efthymiapapadopoulou",
    role: "applied_alumni"
  }
];

module.exports = {
  alumniData
};